### PR TITLE
Make migrations compatible with settings category removal

### PR DESCRIPTION
**Pull request by stejskalleos**
See:

https://github.com/theforeman/foreman/pull/9524
https://github.com/theforeman/foreman/pull/9524#issuecomment-1404661119

### CODE REVIEW

**Review by ekohl — CHANGES_REQUESTED** [review]
It still fails. Looks like this also needs a change:
https://github.com/theforeman/puppetdb_foreman/blob/19ade1fb43939513f5795570e6c5683fea51a29f/db/migrate/20170717140010_migrate_puppetdb_api_version_setting.rb#L9

**Comment by stejskalleos** [comment]
Migrations fixed, but now it's failing on webpack:
```
Can't find our webpack executable at /home/jenkins/workspace/puppetdb_foreman-pull-request/label/fast/ruby/2.7/foreman/node_modules/.bin/webpack - have you run `npm install`?
/home/jenkins/workspace/puppetdb_foreman-pull-request/label/fast/ruby/2.7/foreman/lib/tasks/webpack_compile.rake:19:in `block (2 levels) in <top (required)>'
```

Why is webpack involved?

**Comment by ekohl** [comment]
That's a good question, since there is no `package.json` it shouldn't have any webpack resources. It's probably fallout from 
https://github.com/theforeman/jenkins-jobs/commit/ebfdda28aaab0c218b9bceef1fd56575c5dfd425 where `$database` was previously undefined, but now `rake jenkins:integration is run unconditionally. And `jenkins:integration` pulls in `webpack:compile`: https://github.com/theforeman/foreman/blob/4381a7bb7fadf5c3c11f0976343b1b025edf5039/lib/tasks/jenkins.rake#L6

**Comment by ekohl** [comment]
I opened https://github.com/theforeman/jenkins-jobs/pull/337 which I think should fix it.

**Comment by ekohl** [comment]
[test puppetdb_foreman]

**Comment by ekohl** [comment]
[test puppetdb_foreman]

**Review by ekohl — APPROVED** [review]

**Pull request merged**
