### PR TITLE
Fix PuppetDB Dashboard not working with 1.11+

### PR DESCRIPTION
**Pull request by sathieu**

### CODE REVIEW

**Comment by sathieu** [comment]
Fixes #21

**Comment by sathieu** [comment]
Note that I don't know anything about Ruby. Please review.

**Comment by ponsfrilus** [comment]
Patch works on my installation of Foreman 1.11, thanks @sathieu !

**Comment by Conzar** [comment]
Patch works on my 1.11 installation!

**Comment by sathieu** [comment]
@domcleal Ping: Just to make sure this patch goes in the next 1.11 update. Thanks!

**Comment by domcleal** [comment]
@dLobatog maintains this plugin, not me.

**Comment by dLobatog** [comment]
@sathieu I'll try this out in a moment, thanks

**Comment by dLobatog** [comment]
Merged as 90ddaa01cf9bfe8d42b230afd7ed30ceae3d4724, thanks @sathieu ! I'll update the debs/rpms shortly and link to that here.

**Comment by dLobatog** [comment]
rpms - https://github.com/theforeman/foreman-packaging/pull/1106
debs - https://github.com/theforeman/foreman-packaging/pull/1105

**Comment by sathieu** [comment]
@dLobatog thanks
@domcleal Sorry for the noise then

**Pull request closed without merging**
